on:
  push:
    branches:
      - main

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    name: Push to DockerHub
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/aws-local-ui:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - id: update_metadata_docker_hub
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          workflow: update-metadata-docker-hub
        
